server:
  port: 9001
spring:
  application:
    name: oa-lcf-demo-web
  thymeleaf:
    cache: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
    registry-fetch-interval-seconds: 1
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 1

feign:
  hystrix:
    enabled: false
