server:
  port: 8001
spring:
  application:
    name: oa-lcf-demo-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/数据库?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    #password: 密码

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.oasys.oaapi.entity
  global-config:
    db-config:
      id-type: auto

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
    registry-fetch-interval-seconds: 1
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 1

feign:
  hystrix:
    enabled: false

